# -*- coding: utf-8 -*-
"""MaxVerstappen_DataCollection_MonzaGP_2025_Pole

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uzMm8VJqPVTfsky9mphXX7cW_IvH9Qf_
"""

# installing the library to get F1 data
!pip install fastf1 pandas

import fastf1
import pandas as pd

# 1. setup
# grabbing Monza 2025 quali lap
session = fastf1.get_session(2025, 'Italian Grand Prix', 'Q')
session.load()

# 3. get Verstappen's fastest lap
lap = session.laps.pick_driver('VER').pick_fastest()
telemetry = lap.get_telemetry()

# 4. data clean up
# simulink needs time and speed
data = pd.DataFrame()
data['Time'] = telemetry['Time'].dt.total_seconds()
data['Velocity_KPH'] = telemetry['Speed']

# 5. save to a CSV file
csv_filename = 'verstappen_monza_2025.csv'
data.to_csv(csv_filename, index=False)